`FileAppender` GZIP support
gchq/stroom pull request #2097
Opened 2021-03-16 12:43 UTC by p-kimberley

Provide an option to apply GZIP compression to `FileAppender` output files. Closes #759.

2021-03-16 13:01 UTC, at055612 requested changes

2021-03-16 13:01 UTC, at055612 commented on stroom-pipeline/src/main/java/stroom/pipeline/server/writer/FileAppender.java
> +    public void setUseCompression(final boolean useCompression) { this.useCompression = useCompression; }
public void setUseCompression(final boolean useCompression) {
        this.useCompression = useCompression;
    }

2021-03-16 13:01 UTC, at055612 commented on stroom-pipeline/src/main/java/stroom/pipeline/server/writer/FileAppender.java
> +            else {
} else {

2021-03-16 13:01 UTC, at055612 commented on stroom-pipeline/src/main/java/stroom/pipeline/server/writer/FileAppender.java
> +                byteCountOutputStream = new ByteCountOutputStream(new GZIPOutputStream(new BufferedOutputStream(Files.newOutputStream(lockFile))));
Possibly too long.  We have a hard limit of 120chrs in v7

2021-03-16 13:32 UTC, p-kimberley reviewed
Thanks @at055612

2021-03-17 10:34 UTC, stroomdev66 commented
What about `RollingFileAppender`?

2021-03-17 10:41 UTC, p-kimberley commented
@stroomdev66 Fair enough :) Quite a simple change as well, will get to it shortly.

Won't back-port changes to 5.5 though - unless there's an urgent need for them.

2021-04-02 08:53 UTC, merged